apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: huskyapply
data:
  # Spring Boot Configuration
  server.port: "8080"
  
  # Database Configuration
  spring.datasource.url: "jdbc:postgresql://postgres-service:5432/huskyapply"
  spring.datasource.driver-class-name: "org.postgresql.Driver"
  spring.jpa.hibernate.ddl-auto: "validate"
  spring.jpa.show-sql: "false"
  spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  
  # Flyway Configuration
  spring.flyway.enabled: "true"
  spring.flyway.locations: "classpath:db/migration"
  spring.flyway.baseline-on-migrate: "true"
  
  # RabbitMQ Configuration
  spring.rabbitmq.host: "rabbitmq-service"
  spring.rabbitmq.port: "5672"
  spring.rabbitmq.virtual-host: "/"
  rabbitmq.exchange.name: "jobs.exchange"
  rabbitmq.routing.key: "jobs.process"
  rabbitmq.queue.name: "jobs.queue"
  
  # Redis Configuration
  spring.redis.host: "redis-service"
  spring.redis.port: "6379"
  spring.redis.timeout: "2000ms"
  spring.redis.lettuce.pool.max-active: "8"
  
  # Actuator Configuration
  management.endpoints.web.exposure.include: "health,metrics,prometheus,info"
  management.endpoint.health.show-details: "always"
  management.metrics.export.prometheus.enabled: "true"
  
  # AWS S3 Configuration
  aws.s3.region: "us-east-1"
  
  # Internal API Configuration
  gateway.internal.url: "http://gateway-service:8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: brain-config
  namespace: huskyapply
data:
  # FastAPI Configuration
  PORT: "8000"
  HOST: "0.0.0.0"
  
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "husky"
  RABBITMQ_QUEUE: "jobs.queue"
  
  # Gateway Configuration
  GATEWAY_INTERNAL_URL: "http://gateway-service:8080"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: huskyapply
data:
  POSTGRES_DB: "huskyapply"
  POSTGRES_USER: "husky"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: huskyapply
data:
  RABBITMQ_DEFAULT_USER: "husky"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: huskyapply
data:
  # Redis Configuration
  maxmemory: "256mb"
  maxmemory-policy: "allkeys-lru"
  save: "900 1 300 10 60 10000"