# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import job_processing_pb2 as job__processing__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in job_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobProcessingServiceStub(object):
    """Brain Job Processing Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/com.huskyapply.brain.proto.JobProcessingService/SubmitJob',
                request_serializer=job__processing__pb2.JobSubmissionRequest.SerializeToString,
                response_deserializer=job__processing__pb2.JobSubmissionResponse.FromString,
                _registered_method=True)
        self.StreamJobUpdates = channel.unary_stream(
                '/com.huskyapply.brain.proto.JobProcessingService/StreamJobUpdates',
                request_serializer=job__processing__pb2.JobUpdateRequest.SerializeToString,
                response_deserializer=job__processing__pb2.JobUpdateResponse.FromString,
                _registered_method=True)
        self.ProcessJobBatch = channel.stream_stream(
                '/com.huskyapply.brain.proto.JobProcessingService/ProcessJobBatch',
                request_serializer=job__processing__pb2.BatchJobRequest.SerializeToString,
                response_deserializer=job__processing__pb2.BatchJobResponse.FromString,
                _registered_method=True)
        self.GetJobResult = channel.unary_unary(
                '/com.huskyapply.brain.proto.JobProcessingService/GetJobResult',
                request_serializer=job__processing__pb2.JobResultRequest.SerializeToString,
                response_deserializer=job__processing__pb2.JobResultResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/com.huskyapply.brain.proto.JobProcessingService/HealthCheck',
                request_serializer=job__processing__pb2.HealthRequest.SerializeToString,
                response_deserializer=job__processing__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/com.huskyapply.brain.proto.JobProcessingService/CancelJob',
                request_serializer=job__processing__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=job__processing__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.GetProcessingMetrics = channel.unary_unary(
                '/com.huskyapply.brain.proto.JobProcessingService/GetProcessingMetrics',
                request_serializer=job__processing__pb2.MetricsRequest.SerializeToString,
                response_deserializer=job__processing__pb2.MetricsResponse.FromString,
                _registered_method=True)


class JobProcessingServiceServicer(object):
    """Brain Job Processing Service
    """

    def SubmitJob(self, request, context):
        """Submit a single job for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJobUpdates(self, request, context):
        """Stream job updates in real-time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessJobBatch(self, request_iterator, context):
        """Process multiple jobs in a batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobResult(self, request, context):
        """Get job processing result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel a job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessingMetrics(self, request, context):
        """Get processing metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=job__processing__pb2.JobSubmissionRequest.FromString,
                    response_serializer=job__processing__pb2.JobSubmissionResponse.SerializeToString,
            ),
            'StreamJobUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJobUpdates,
                    request_deserializer=job__processing__pb2.JobUpdateRequest.FromString,
                    response_serializer=job__processing__pb2.JobUpdateResponse.SerializeToString,
            ),
            'ProcessJobBatch': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessJobBatch,
                    request_deserializer=job__processing__pb2.BatchJobRequest.FromString,
                    response_serializer=job__processing__pb2.BatchJobResponse.SerializeToString,
            ),
            'GetJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobResult,
                    request_deserializer=job__processing__pb2.JobResultRequest.FromString,
                    response_serializer=job__processing__pb2.JobResultResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=job__processing__pb2.HealthRequest.FromString,
                    response_serializer=job__processing__pb2.HealthResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=job__processing__pb2.CancelJobRequest.FromString,
                    response_serializer=job__processing__pb2.CancelJobResponse.SerializeToString,
            ),
            'GetProcessingMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessingMetrics,
                    request_deserializer=job__processing__pb2.MetricsRequest.FromString,
                    response_serializer=job__processing__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.huskyapply.brain.proto.JobProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.huskyapply.brain.proto.JobProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobProcessingService(object):
    """Brain Job Processing Service
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.huskyapply.brain.proto.JobProcessingService/SubmitJob',
            job__processing__pb2.JobSubmissionRequest.SerializeToString,
            job__processing__pb2.JobSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJobUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.huskyapply.brain.proto.JobProcessingService/StreamJobUpdates',
            job__processing__pb2.JobUpdateRequest.SerializeToString,
            job__processing__pb2.JobUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessJobBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.huskyapply.brain.proto.JobProcessingService/ProcessJobBatch',
            job__processing__pb2.BatchJobRequest.SerializeToString,
            job__processing__pb2.BatchJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.huskyapply.brain.proto.JobProcessingService/GetJobResult',
            job__processing__pb2.JobResultRequest.SerializeToString,
            job__processing__pb2.JobResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.huskyapply.brain.proto.JobProcessingService/HealthCheck',
            job__processing__pb2.HealthRequest.SerializeToString,
            job__processing__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.huskyapply.brain.proto.JobProcessingService/CancelJob',
            job__processing__pb2.CancelJobRequest.SerializeToString,
            job__processing__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessingMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.huskyapply.brain.proto.JobProcessingService/GetProcessingMetrics',
            job__processing__pb2.MetricsRequest.SerializeToString,
            job__processing__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GatewayCallbackServiceStub(object):
    """Gateway Callback Service (for Brain to notify Gateway)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateJobStatus = channel.unary_unary(
                '/com.huskyapply.brain.proto.GatewayCallbackService/UpdateJobStatus',
                request_serializer=job__processing__pb2.JobStatusUpdate.SerializeToString,
                response_deserializer=job__processing__pb2.StatusUpdateAck.FromString,
                _registered_method=True)


class GatewayCallbackServiceServicer(object):
    """Gateway Callback Service (for Brain to notify Gateway)
    """

    def UpdateJobStatus(self, request, context):
        """Update job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayCallbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJobStatus,
                    request_deserializer=job__processing__pb2.JobStatusUpdate.FromString,
                    response_serializer=job__processing__pb2.StatusUpdateAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.huskyapply.brain.proto.GatewayCallbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.huskyapply.brain.proto.GatewayCallbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayCallbackService(object):
    """Gateway Callback Service (for Brain to notify Gateway)
    """

    @staticmethod
    def UpdateJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.huskyapply.brain.proto.GatewayCallbackService/UpdateJobStatus',
            job__processing__pb2.JobStatusUpdate.SerializeToString,
            job__processing__pb2.StatusUpdateAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
