"""
Type stub file for job_processing_pb2_grpc.py generated by gRPC compiler.
This helps static type checkers like Pyright understand the generated gRPC code.
"""

from typing import Iterator, Any
import grpc
from grpc import aio
from . import job_processing_pb2 as _job_processing_pb2

# Job Processing Service - Servicer (server-side)
class JobProcessingServiceServicer:
    """Service definition for Brain job processing."""

    async def SubmitJob(
        self,
        request: _job_processing_pb2.JobSubmissionRequest,
        context: aio.ServicerContext
    ) -> _job_processing_pb2.JobSubmissionResponse: ...

    async def StreamJobUpdates(
        self,
        request: _job_processing_pb2.JobUpdateRequest,
        context: aio.ServicerContext
    ) -> Iterator[_job_processing_pb2.JobUpdateResponse]: ...

    async def ProcessJobBatch(
        self,
        request_iterator: Iterator[_job_processing_pb2.BatchJobRequest],
        context: aio.ServicerContext
    ) -> Iterator[_job_processing_pb2.BatchJobResponse]: ...

    async def GetJobResult(
        self,
        request: _job_processing_pb2.JobResultRequest,
        context: aio.ServicerContext
    ) -> _job_processing_pb2.JobResultResponse: ...

    async def HealthCheck(
        self,
        request: _job_processing_pb2.HealthRequest,
        context: aio.ServicerContext
    ) -> _job_processing_pb2.HealthResponse: ...

    async def CancelJob(
        self,
        request: _job_processing_pb2.CancelJobRequest,
        context: aio.ServicerContext
    ) -> _job_processing_pb2.CancelJobResponse: ...

    async def GetProcessingMetrics(
        self,
        request: _job_processing_pb2.MetricsRequest,
        context: aio.ServicerContext
    ) -> _job_processing_pb2.MetricsResponse: ...

# Job Processing Service - Stub (client-side)
class JobProcessingServiceStub:
    """Client stub for Brain job processing service."""

    def __init__(self, channel: grpc.Channel) -> None: ...

    def SubmitJob(
        self,
        request: _job_processing_pb2.JobSubmissionRequest,
        timeout: float | None = None,
        metadata: Any | None = None,
        credentials: Any | None = None,
        wait_for_ready: bool | None = None,
        compression: bool | None = None
    ) -> _job_processing_pb2.JobSubmissionResponse: ...

    def StreamJobUpdates(
        self,
        request: _job_processing_pb2.JobUpdateRequest,
        timeout: float | None = None,
        metadata: Any | None = None,
        credentials: Any | None = None,
        wait_for_ready: bool | None = None,
        compression: bool | None = None
    ) -> Iterator[_job_processing_pb2.JobUpdateResponse]: ...

    def GetJobResult(
        self,
        request: _job_processing_pb2.JobResultRequest,
        timeout: float | None = None,
        metadata: Any | None = None,
        credentials: Any | None = None,
        wait_for_ready: bool | None = None,
        compression: bool | None = None
    ) -> _job_processing_pb2.JobResultResponse: ...

    def HealthCheck(
        self,
        request: _job_processing_pb2.HealthRequest,
        timeout: float | None = None,
        metadata: Any | None = None,
        credentials: Any | None = None,
        wait_for_ready: bool | None = None,
        compression: bool | None = None
    ) -> _job_processing_pb2.HealthResponse: ...

    def CancelJob(
        self,
        request: _job_processing_pb2.CancelJobRequest,
        timeout: float | None = None,
        metadata: Any | None = None,
        credentials: Any | None = None,
        wait_for_ready: bool | None = None,
        compression: bool | None = None
    ) -> _job_processing_pb2.CancelJobResponse: ...

    def GetProcessingMetrics(
        self,
        request: _job_processing_pb2.MetricsRequest,
        timeout: float | None = None,
        metadata: Any | None = None,
        credentials: Any | None = None,
        wait_for_ready: bool | None = None,
        compression: bool | None = None
    ) -> _job_processing_pb2.MetricsResponse: ...

# Gateway Callback Service - Servicer (server-side)
class GatewayCallbackServiceServicer:
    """Service definition for Gateway callbacks."""

    async def UpdateJobStatus(
        self,
        request: _job_processing_pb2.JobStatusUpdate,
        context: aio.ServicerContext
    ) -> _job_processing_pb2.StatusUpdateAck: ...

# Gateway Callback Service - Stub (client-side)
class GatewayCallbackServiceStub:
    """Client stub for Gateway callback service."""

    def __init__(self, channel: grpc.Channel) -> None: ...

    def UpdateJobStatus(
        self,
        request: _job_processing_pb2.JobStatusUpdate,
        timeout: float | None = None,
        metadata: Any | None = None,
        credentials: Any | None = None,
        wait_for_ready: bool | None = None,
        compression: bool | None = None
    ) -> _job_processing_pb2.StatusUpdateAck: ...

# Service registration functions
def add_JobProcessingServiceServicer_to_server(
    servicer: JobProcessingServiceServicer,
    server: grpc.aio.Server
) -> None: ...

def add_GatewayCallbackServiceServicer_to_server(
    servicer: GatewayCallbackServiceServicer,
    server: grpc.aio.Server
) -> None: ...
