name: HuskyApply CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Run Gateway tests
        run: cd gateway && mvn test

  test-brain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: pip install uv
      
      - name: Install dependencies
        run: cd brain && uv sync --extra test
      
      - name: Run Brain tests
        run: cd brain && uv run pytest

  build-gateway:
    runs-on: ubuntu-latest
    needs: test-gateway
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Gateway Docker image
        run: docker build -t huskyapply-gateway:latest ./gateway

  build-brain:
    runs-on: ubuntu-latest
    needs: test-brain
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Brain Docker image
        run: docker build -t huskyapply-brain:latest ./brain